sonar.projectKey=sebseb10_ITU-MiniTwit
sonar.organization=sebseb10
sonar.sources=src
sonar.tests=test
sonar.language=cs
sonar.exclusions=**/obj/**,**/bin/**,**/*.Designer.cs
sonar.test.exclusions=**/obj/**,**/bin/**
