name: Auto Label Issues
on:
  issues: 
    types:
      - opened
      - edited
jobs:
  auto-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.issue.title.toLowerCase();
            const body = context.payload.issue.body ? context.payload.issue.body.toLowerCase() : '';
            const issueNumber = context.payload.issue.number;
            
            //Label Rules
            const labelRules = [
              { label: 'bug', keywords: ['bug', 'error', 'crash', 'fix', 'issue', 'problem'] },
              { label: 'enhancement', keywords: ['feature', 'enhancement', 'improvement', 'add', 'new'] },
              { label: 'documentation', keywords: ['doc', 'documentation', 'readme', 'wiki'] },
              { label: 'question', keywords: ['question', 'help', 'how to', '?'] },
              { label: 'ui', keywords: ['ui', 'interface', 'design', 'visual', 'layout'] },
              { label: 'backend', keywords: ['api', 'database', 'server', 'endpoint'] },
            ];
            //Labels based on context ÙwÚ
            const labelsToAdd = [];
            for (const rule of labelRules) {
              if (rule.keywords.some(keyword => title.includes(keyword) || body.includes(keyword))) {
                labelsToAdd.push(rule.label);
              }
            }
            if (labelsToAdd.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                labels: labelsToAdd
              });
            
              console.log(`Added labels: ${labelsToAdd.join(', ')} to issue #${issueNumber}`);
            }