#Co-Author: sesv@itu.dk, anys@itu.dk, luki@itu.dk, LLM (Chatgpt.com) samt inspiration fået fra Oliver Flinck Sheye 189235422+osheITU@users.noreply.github.com

name: Build, Test, and Release
run-name: ${{ github.actor }} is building and possibly releasing ${{ github.ref_name }}
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
permissions: 
  contents: write
jobs:
 
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build project
        run: dotnet build -c Release --no-restore

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x
          
      - name: Run tests
        run: dotnet test -c Release

  prepare-release:
    name: Prepare Release
    needs: test              
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    outputs: 
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Chirp ${{ github.ref_name }}"
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  publish-web:
    name: Publish Web Application
    needs: prepare-release
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x
      
      - name: Publish Web App
        run: |
          release_name="Chirp-Razor-${{ github.ref_name }}"
          
          dotnet publish "src/Chirp.Razor/Chirp.Razor.csproj" \
            -c Release \
            -o "${release_name}" \
            --self-contained false
          
          7z a "${release_name}.zip" "${release_name}/."
                    
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
          with:
            upload_url: ${{ needs.prepare-release.outputs.upload_url }}
            asset_path: "Chirp-Razor-${{ github.ref_name }}.zip"
            asset_name: "Chirp-Razor-${{ github.ref_name }}.zip"
            asset_content_type: application/zip
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}