#Co-Author: sesv@itu.dk, anys@itu.dk, luki@itu.dk, LLM (Chatgpt.com) samt inspiration fået fra Oliver Flinck Sheye 189235422+osheITU@users.noreply.github.com

name: Build, Test, and Release
run-name: ${{ github.actor }} is building and possibly releasing ${{ github.ref_name }}
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
permissions: 
  contents: write
jobs:
 
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build project
        run: dotnet build -c Release --no-restore

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x
          
      - name: Run tests
        run: dotnet test -c Release

  publish-and-release-webapp:
    name: Publish and Release Web App
    needs: test
    runs-on: ubuntu-latest
    
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        
      - name: Setup .Net 8
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x
          
      - name: Publish Web App for Release
        run: |
          dotnet publish "src/Chirp.Web/Chirp.Web.csproj" -c Release -o release-output --self-contained false
          zip -r "Chirp-Web-${{ github.ref_name }}.zip" ./release-output
          
      - name: Create GitHub Release and Upload Artifact
        uses: softprops/action-gh-release@v2
        with:
          name: "Chirp ${{ github.ref_name }}"
          generate_release_notes: true
          files: "Chirp-Web-${{ github.ref_name }}.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
