name: CI.yml
on:
  push:
    branches: ['**']
    tags-ignore: ['v*']
  pull_request:
    branches: ['main']
    
concurrency: 
  group: ci-${{ github.ref}}
  cancel-in-progress: true
  
permissions: 
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: setup-dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x
          cache: true
      - run: dotnet restore
      - run: dotnet build -c Release --no-restore 
  test:
    name: test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: setup-dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x
          cache: true
      - run: dotnet test -c Release --no-build --collect:"XPlat Code Coverage"
      - uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: **/TestResults/*
