name: Weekly Release

on:
  schedule:
    # Every Monday at 00:00 UTC
    - cron: '0 0 * * 1'

permissions:
  contents: write

jobs:
  release:
    name: Create weekly release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set tag name
        id: vars
        run: echo "tag=v$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ steps.vars.outputs.tag }}" \
            --repo="$GITHUB_REPOSITORY" \
            --title="Weekly Release ${{ steps.vars.outputs.tag }}" \
            --generate-notes
