name: Publish executable

on:
  push:
    tags: ['v*']
  release:
    types: [published]

permissions:
  contents: write   

jobs:
  release:
    name: Release (${{ matrix.kind }})
    strategy:
      fail-fast: false
      matrix:
        kind: ['linux', 'windows', 'macOS-x64', 'macOS-arm64']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS-x64
            os: macos-latest      # Intel macOS runner
            target: osx-x64
          - kind: macOS-arm64
            os: macos-latest      # Apple Silicon runner
            target: osx-arm64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x
          cache: false  

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build -c Release --no-restore

      - name: Run tests
        run: dotnet test -c Release --no-build

      - name: Publish Chirp WebApp (Single File)
        shell: bash
        run: |
          set -euo pipefail

          # Determine tag name
          tag="${{ github.event_name == 'release' && github.event.release.tag_name || github.ref_name }}"
          rid="${{ matrix.target }}"
          app="Chirp-Web"
          project="src/Chirp.Web/Chirp.Web.csproj"
          outdir="${app}-${tag}-${rid}"

          # Disable macOS codesigning for cross-builds
          mac_sign=""
          if [[ "$rid" == osx-* ]]; then
            mac_sign="-p:EnableMacOSCodeSign=false"
          fi

        

          # Build single-file, framework-dependent
          dotnet publish "$project" \
            -c Release \
            --framework net8.0 \
            --runtime "$rid" \
            --self-contained false \
            -p:PublishSingleFile=true \
            -p:PublishTrimmed=false \
            -p:DebugType=none -p:DebugSymbols=false \
            $mac_sign \
            -o "$outdir"

          # Zip the result with one root folder inside
          if [ "$rid" = "win-x64" ]; then
            7z a -tzip "${outdir}.zip" "$outdir"
          else
            zip -r "${outdir}.zip" "$outdir"
          fi

          rm -rf "$outdir"

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Chirp ${{ github.event_name == 'release' && github.event.release.tag_name || github.ref_name }}"
          generate_release_notes: true
          files: |
            Chirp-Web-${{ github.event_name == 'release' && github.event.release.tag_name || github.ref_name }}-${{ matrix.target }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
