name: Release (tagged build)
on:
  push:
    tags: ['v*']  # git push origin v1.2.3

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x
          # IMPORTANT: do NOT set "cache: true" unless you commit packages.lock.json

      # Build & test before publishing
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Test
        run: dotnet test -c Release --no-build

      - name: Publish single-file (linux/win/mac) and zip
        shell: bash
        run: |
          set -euo pipefail
          tag="${{ github.ref_name }}"
          project="src/Chirp.Web/Chirp.Web.csproj"
          app="Chirp-Web"
          rids=(linux-x64 win-x64 osx-x64)   # add osx-arm64 if desired

          mkdir -p out
          for rid in "${rids[@]}"; do
            outdir="${app}-${tag}-${rid}"

            # Disable macOS code signing when cross-building on Linux
            mac_sign=""
            if [[ "$rid" == osx-* ]]; then
              mac_sign="-p:EnableMacOSCodeSign=false"
            fi

            dotnet publish "$project" -c Release \
              --framework net8.0 \
              --runtime "$rid" \
              --self-contained false \
              -p:PublishSingleFile=true \
              -p:PublishTrimmed=false \
              -p:DebugType=none -p:DebugSymbols=false \
              $mac_sign \
              -o "$outdir"

            # Zip the folder (keeps a single root in the archive)
            zip -r "out/${outdir}.zip" "$outdir"
            rm -rf "$outdir"
          done

          ls -l out

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          name: "Chirp ${{ github.ref_name }}"
          generate_release_notes: true
          files: out/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
