# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - bdsa2025group6chirp

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: bdsa2025group6chirp
  CHIRP_WEB_PATH: "src/Chirp.Web/Chirp.Web.csproj"
  SOLUTION_PATH: "Chirp.sln"
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      
      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}
        
      - name: Build with dotnet
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

      - name: dotnet publish
        run: dotnet publish ${{ env.CHIRP_WEB_PATH }} -c Release --no-restore --no-build -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6D017B6DE2BF43BF818D6B33C0721C80 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0F2B3B604D9A4D23BB5A4C97E79D52E9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_270E831353B945BA862CE68A7E459BDA }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bdsa2025group6chirp'
          slot-name: 'Production'
          package: .

          
