# This workflow is from: https://github.com/marketplace/actions/github-project-automation
# Intended to automate the project board.

name: Move new issues into No Status

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.1
        with:
          project-url: "https://github.com/orgs/ITU-BDSA2025-GROUP6/projects/4"
          github-token: ${{ secrets.GITHUB_TOKEN }}
